### ISSUE TITLE
Метод publishGame класса GameStore не создает объект игры с заданными заголовком и жанром

### ISSUE THREAD

**Issue by Elenaclinic** [Elenaclinic/javaqa-team-diplom#5]
##  Описание
При выполнении теста shouldAddGame, метод  publishGame не создал игру

## Локализация дефекта
[код программы](https://github.com/Elenaclinic/javaqa-team-diplom/blob/6e17e76169ddbbce68ed2749ffce6efac405d55a/src/main/java/ru/netology/GameStore.java#L38)

## Шаги воспроизведения
1. Открыть [тест](https://github.com/Elenaclinic/javaqa-team-diplom/blob/6e17e76169ddbbce68ed2749ffce6efac405d55a/src/test/java/ru/netology/GameStoreTest.java#L14) в IDEA
2. Запустить тест
3. Посмотреть на вывод в консоли

Ожидаемый результат: true
Фактический результат: false

## Скриншот 
![image](https://user-images.githubusercontent.com/115639950/210975837-98a673d0-7235-42be-8d26-0d1c0fb33ef4.png)

## Окружение
Операционная система: Windows 10
IDE: IntelliJ IDEA 2021.1 (Community Edition)
Java: Open JDK 11

**Comment by Oife88** [comment]
исправлено
