### ISSUE TITLE
 Не суммируется общее количество времени всех игроков, проведённого за играми каталога

### ISSUE THREAD

**Issue by Elenaclinic** [Elenaclinic/javaqa-team-diplom#6]
## Описание 
При выполнении теста shouldSumPlayedTime в классе GameStoreTest не суммируется общее количество времени игроков 
## Локация дефекта
[код программы](https://github.com/Elenaclinic/javaqa-team-diplom/blob/6e17e76169ddbbce68ed2749ffce6efac405d55a/src/main/java/ru/netology/GameStore.java#L109)
## Шаги воспроизведения
1. Открыть [тест](https://github.com/Elenaclinic/javaqa-team-diplom/blob/6e17e76169ddbbce68ed2749ffce6efac405d55a/src/test/java/ru/netology/GameStoreTest.java#L56) в IDEA
2. Запустить тест
3. Посмотреть на вывод в консоли

Ожидаемый результат: 7
Фактический результат: 0

##Скриншот
![image](https://user-images.githubusercontent.com/115639950/211151215-0b038939-1ce2-4618-acc0-5be532ae1f11.png)

## Окружение
Операционная система: Windows 10
IDE: IntelliJ IDEA 2021.1 (Community Edition)
Java: Open JDK 11

**Comment by Oife88** [comment]
исправлено, тест проходит
