### ISSUE TITLE
Не регистрируется количество времени, которое проиграл игрок за игрой каталога 

### ISSUE THREAD

**Issue by Elenaclinic** [Elenaclinic/javaqa-team-diplom#7]
## Описание 
При выполнении теста playTimeCheck в классе GameStoreTest 
Не происходит регистрации времени ,которое проиграл игрок за игрой данного каталога
## Локация дефекта
[Код программы](https://github.com/Elenaclinic/javaqa-team-diplom/blob/063c6b58827e9d4f7e476f8a6299842d5a9ed0af/src/main/java/ru/netology/Player.java#L57)
## Шаги воспроизведения

1. Открыть [тест](https://github.com/Elenaclinic/javaqa-team-diplom/blob/6e17e76169ddbbce68ed2749ffce6efac405d55a/src/test/java/ru/netology/GameStoreTest.java#L37) в IDEA
2. Запустить тест
3. Посмотреть на вывод в консоли

Ожидаемый результат: 7
Фактический результат: 0

## Скриншот
![image](https://user-images.githubusercontent.com/115639950/211152243-b9deede1-8780-4668-8467-11fbb33c5050.png)

## Окружение
Операционная система: Windows 10
IDE: IntelliJ IDEA 2021.1 (Community Edition)
Java: Open JDK 11

**Comment by Oife88** [comment]
исправлено, тес проходит
