### ISSUE TITLE
метод containsGame в классе GameStore неверно проверяет наличие игры в каталоге

### ISSUE THREAD

**Issue by Elenaclinic** [Elenaclinic/javaqa-team-diplom#8]
## Описание 
После добавления методом publishGame и последующей проверке наличия игры в каталоге методом containsGame игра не обнаруживается

## Локация дефекта
[код программы](https://github.com/Elenaclinic/javaqa-team-diplom/blob/6e17e76169ddbbce68ed2749ffce6efac405d55a/src/main/java/ru/netology/GameStore.java#L51)

## Шаги воспроизведения
1. Открыть [тест](https://github.com/Elenaclinic/javaqa-team-diplom/blob/6e17e76169ddbbce68ed2749ffce6efac405d55a/src/test/java/ru/netology/GameStoreTest.java#L57) в IDEA
2. Запустить тест
3. Посмотреть на вывод в консоли

Oжидаемый результат - true
Фактический результат - false

## Скриншот
![image](https://user-images.githubusercontent.com/115639950/211153388-871196f7-16ad-41a9-9f4d-54b7683e3f12.png)

## Окружение
Операционная система: Windows 10
IDE: IntelliJ IDEA 2021.1 (Community Edition)
Java: Open JDK 11

**Comment by Oife88** [comment]
Исправлено

**Comment by Oife88** [comment]
исправлено, тест проходит
